# Generated by Django 3.2 on 2024-10-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('order_placed', 'Order Placed'), ('assigned', 'Assigned'), ('picked', 'Picked'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
